inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    # - !ruby/regexp /old_and_unused\.rb$/

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true

Naming/RescuedExceptionsVariableName:
  Enabled: true
  PreferredName: e

Rails/HttpStatus:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: true
  Whitelist:
    - find_by_sql
    - find_by_ids_ordered
    - find_by_controller
    - find_by_permalink_or_raise_not_found
    - find_by_code
    - find_by_slug
    - find_by_teacher_token
    - find_by_affiliate_token
    - find_by_code_and_country_code

Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

# Layouts

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: indent

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument

Layout/ArrayAlignment:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: either

Layout/BlockEndNewline:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: case

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true
  AutoCorrect: true

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyComment:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: false
  NumberOfEmptyLines: 1

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundArguments:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  AutoCorrect: true
  EnforcedStyleAlignWith: keyword

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false
  AllowBeforeTrailingComments: false
  ForceEqualSignAlignment: false
  Exclude:
    - Guardfile

Layout/AssignmentIndentation:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/IndentationWidth:
  Enabled: true
  Width: 2
  IgnoredPatterns: []

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: special_for_inner_method_call_in_parentheses

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/InitialIndentation:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: aligned

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: aligned

Layout/RescueEnsureAlignment:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true
  EnforcedStyleInsidePipes: no_space

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceAroundOperators:
  Enabled: true
  AllowForAlignment: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true
  AllowForAlignment: true

Layout/SpaceBeforeSemicolon:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  Enabled: true
  EnforcedStyle: require_space

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
  SupportedStylesForEmptyBraces: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Layout/SpaceInsideParens:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline

Layout/TrailingWhitespace:
  Enabled: true
  AllowInHeredoc: false

# linters

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/RedundantStringCoercion:
  Enabled: true

Lint/ToJSON:
  Enabled: true

Lint/RedundantSplatExpansion:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true
  IgnoreEmptyBlocks: false
  AllowUnusedKeywordArguments: false

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: false
  IgnoreEmptyMethods: false
  IgnoreNotImplementedMethods: true
  Exclude:
    - "lib/sidekiq/pre_production_middleware.rb"
    - "lib/sidekiq/server/rescue_smtp_syntax_error_middleware.rb"
    - "app/graphql/mutations/save_video_item_user_progression.rb"

Lint/NonDeterministicRequireOrder:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/Debugger:
  Enabled: true

# Styles

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/NumericPredicate:
  Enabled: true
  EnforcedStyle: predicate
  AutoCorrect: true

Style/BarePercentLiterals:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
  AutoCorrect: true

Style/PercentQLiterals:
  EnforcedStyle: lower_case_q

# Performance

Performance/Casecmp:
  Enabled: true

Performance/InefficientHashSearch:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/Size:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/Detect:
  Enabled: true

# Specs

Capybara/CurrentPathExpectation:
  Enabled: true

Capybara/FeatureMethods:
  Enabled: true

FactoryBot/AttributeDefinedStatically:
  Exclude:
    - "spec/factories/project_factory.rb"

FactoryBot/FactoryClassName:
  Enabled: true

FactoryBot/CreateList:
  Enabled: true

RSpec/BeEql:
  Enabled: true

RSpec/DescribedClass:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/ExampleWording:
  Enabled: true

RSpec/ExpectChange:
  Enabled: true

RSpec/ImplicitExpect:
  Enabled: true

RSpec/ImplicitSubject:
  Enabled: true

RSpec/LeadingSubject:
  Enabled: true

RSpec/NotToNot:
  Enabled: true

RSpec/ReturnFromStub:
  Enabled: true
  EnforcedStyle: block

RSpec/HookArgument:
  Enabled: true

RSpec/HooksBeforeExamples:
  Enabled: true

RSpec/PredicateMatcher:
  Enabled: true

RSpec/ContextMethod:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/FilePath:
  Enabled: false
  IgnoreMethods: true

RSpec/InstanceVariable:
  Enabled: true

RSpec/IteratedExpectation:
  Enabled: true
  Exclude:
    - "spec/steps/course_steps.rb"

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/LetSetup:
  Enabled: true

RSpec/DescribeClass:
  Enabled: true
