language: ruby
rvm:
  - 2.7.2
cache:
  - bundler
before_install:
  - nvm install --lts
before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rails assets:precompile
